# -*- coding: utf-8 -*-
"""finetuning_summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rD31EQ3EeSImEBZSC4_0JiXzG0T6uoMm
"""

from google.colab import drive
drive.mount('/content/drive')

# Limpa ambiente
!pip uninstall -y datasets peft transformers trl accelerate bitsandbytes

# Unsloth (fonte oficial)
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"

# Stack COMPATÍVEL com Unsloth Zoo (2025)
!pip install \
  peft>=0.13.0 \
  datasets==4.3.0 \
  transformers==4.57.3 \
  trl==0.18.2 \
  accelerate \
  bitsandbytes

import os
os.kill(os.getpid(), 9)

import trl, peft, datasets, transformers

print("trl:", trl.__version__)            # 0.18.2
print("peft:", peft.__version__)          # >= 0.13.x
print("datasets:", datasets.__version__)  # 4.3.0
print("transformers:", transformers.__version__)  # 4.57.3

import unsloth
from unsloth import FastLanguageModel, is_bfloat16_supported
import torch
import json
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments

DATA_PATH = "/content/drive/MyDrive/TC3 IA/nomalized_total.json"
OUTPUT_PATH_DATASET = "/content/drive/MyDrive/TC3 IA/output_QA.json"
max_seq_length = 1024
dtype = None
load_in_4bit = True
fourbit_models = [
    "unsloth/mistral-7b-v0.3-bnb-4bit",
    "unsloth/mistral-7b-instruct-v0.3-bnb-4bit",
    "unsloth/llama-3-8b-bnb-4bit",
    "unsloth/llama-3-8b-Instruct-bnb-4bit",
    "unsloth/llama-3-70b-bnb-4bit",
    "unsloth/Phi-3-mini-4k-instruct",
    "unsloth/Phi-3-medium-4k-instruct",
    "unsloth/mistral-7b-bnb-4bit",
    "unsloth/gemma-7b-bnb-4bit",
]

def format_dataset_into_model_input(data):
    # Inicializando as listas para armazenar os dados
    instructions = []
    inputs = []
    outputs = []

    # Processando o dataset de QA
    for item in data["medical_qa"]:
        question = item.get("question", "").strip()
        answer = item.get("normalized_answer", "").strip()

        if not question or not answer:
            continue

        instructions.append(
            "Answer the medical question based on scientific evidence."
        )
        inputs.append(question)
        outputs.append(answer)

    # Criando o dicionário final
    formatted_data = {
        "instruction": instructions,
        "input": inputs,
        "output": outputs
    }

    # Salvando o resultado em um arquivo JSON
    with open(OUTPUT_PATH_DATASET, "w", encoding="utf-8") as output_file:
        json.dump(formatted_data, output_file, indent=4, ensure_ascii=False)

    print(f"Dataset salvo em {OUTPUT_PATH_DATASET}")
    print(f"Total de exemplos: {len(outputs)}")

import json

with open(DATA_PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

format_dataset_into_model_input(data)


model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/llama-3-8b-bnb-4bit",
    max_seq_length=max_seq_length,
    dtype=dtype,
    load_in_4bit=True,
    device_map= None,
)

model = FastLanguageModel.get_peft_model(
      model,
      r = 16,
      target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj"],
      lora_alpha = 16,
      lora_dropout = 0,
      bias = "none",

      use_gradient_checkpointing = "unsloth",
      random_state = 3407,
      use_rslora = False,
      loftq_config = None,
  )

alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{}

### Input:
{}

### Response:
{}"""


EOS_TOKEN = tokenizer.eos_token
def formatting_prompts_func(examples):
    instructions = examples["instruction"]
    inputs       = examples["input"]
    outputs      = examples["output"]
    texts = []
    for instruction, input, output in zip(instructions, inputs, outputs):

        text = alpaca_prompt.format(instruction, input, output) + EOS_TOKEN
        texts.append(text)
    return { "text" : texts, }
pass

from datasets import load_dataset

OUTPUT_PATH_DATASET = "/content/drive/MyDrive/TC3 IA/output_QA.json"
dataset = load_dataset("json", data_files=OUTPUT_PATH_DATASET, split = "train")
dataset = dataset.map(formatting_prompts_func, batched = True,)

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    packing = False,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 60,
        learning_rate = 2e-4,
        fp16 = True,
        bf16 = is_bfloat16_supported(),
        logging_steps = 1,
        no_cuda=False,
        report_to = "none",
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
    ),
)

trainer_stats = trainer.train()

FastLanguageModel.for_inference(model)
inputs = tokenizer(
[
    alpaca_prompt.format(
            "Answer the medical question based on scientific evidence.",
            "Do mitochondria play a role in remodelling lace plant leaves during programmed cell death?",
            "",

    )
], return_tensors = "pt").to("cuda")

outputs = model.generate(**inputs, max_new_tokens = 64, use_cache = True)
tokenizer.batch_decode(outputs, skip_special_tokens=True)

FastLanguageModel.for_inference(model)
inputs = tokenizer(
[
    alpaca_prompt.format(
            "Answer the medical question based on scientific evidence.",
            "Do mitochondria play a role in remodelling lace plant leaves during programmed cell death?",
            "",
    )
], return_tensors = "pt").to("cuda")

from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer)
_ = model.generate(**inputs, streamer = text_streamer, max_new_tokens = 128)

model.save_pretrained("/content/drive/MyDrive/TC3 IA/lora model") # Local saving
tokenizer.save_pretrained("/content/drive/MyDrive/TC3 IA/lora model")

import json

qa_test = []

with open('/content/drive/MyDrive/TC3 IA/output_QA.json', 'r') as f:
    data = json.loads(f.read())

for inst, inp, out in zip(
    data["instruction"],
    data["input"],
    data["output"]
):
    qa_test.append({
        "instruction": inst,
        "input": inp,
        "output": out
    })

from unsloth import FastLanguageModel

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="/content/drive/MyDrive/TC3 IA/lora model",  # 🔴 SEU LoRA treinado
    max_seq_length=max_seq_length,
    dtype=dtype,
    load_in_4bit=load_in_4bit,
)

FastLanguageModel.for_inference(model)

inputs = tokenizer(
    [
        alpaca_prompt.format(
            "Answer the medical question based on scientific evidence.",
            "Does long-term use of proton pump inhibitors increase the risk of chronic kidney disease?",
            "",
        )
    ],
    return_tensors="pt",
).to("cuda")

from transformers import TextStreamer

text_streamer = TextStreamer(tokenizer)

_ = model.generate(
    **inputs,
    streamer=text_streamer,
    max_new_tokens=128,
)